## validation  (to reduce over fitting) (for small data)
---  k fold validation (we select fold size)
--- cross validation
## steps   
    data load
        data quality maintain
    data break
        input(X) and output(y)
    input data(training_X)and testing_X >>>>break x in(25% trained 75 % for testing)
    output data(training_y)and testing_y >>>>break y in(25% trained 75 % for testing)
    >>>>>>>>>validation data
    training accuracy
    model selection:
    -regression or classification
    model fit by supplying traning data
    model evaluate  on testing data
    r2 score
    loss


##### -K fold
--- data fueling technique

##### cross validation

In [48]:
from sklearn.model_selection import cross_val_score

In [49]:
from sklearn.linear_model import Lasso

In [50]:
lasso=Lasso(alpha=0.0001)

extra = clf=svm.SVC(kernal="linear",C=1,random_state=42) #if we dont have kernal

In [51]:
scores=cross_val_score(lasso,x,y,cv=5) #cv=5 break data in 5 chunks or fold

In [52]:
scores

array([ 0.63950653,  0.71407436,  0.58699256,  0.07962292, -0.2494459 ])

In [53]:
scores.mean()

0.354150091807942

In [54]:
scores.std()

0.37546842370634664

In [61]:
cars = pd.read_csv("car_data.csv")

In [64]:
car = pd.read_csv("cleaned_car_data.csv",index_col=0)

In [65]:
car

name   company        year   Price  kms_driven  \
0       Hyundai Santro Xing   Hyundai  2007-01-01   80000       45000   
1       Mahindra Jeep CL550  Mahindra  2006-01-01  425000          40   
2         Hyundai Grand i10   Hyundai  2014-01-01  325000       28000   
3    Ford EcoSport Titanium      Ford  2014-01-01  575000       36000   
4                 Ford Figo      Ford  2012-01-01  175000       41000   
..                      ...       ...         ...     ...         ...   
719      Maruti Suzuki Ritz    Maruti  2011-01-01  270000       50000   
720          Tata Indica V2      Tata  2009-01-01  110000       30000   
721    Toyota Corolla Altis    Toyota  2009-01-01  300000      132000   
722            Tata Zest XM      Tata  2018-01-01  260000       27000   
723      Mahindra Quanto C8  Mahindra  2013-01-01  390000       40000   

    fuel_type  
0      Petrol  
1      Diesel  
2      Petrol  
3      Diesel  
4      Diesel  
..        ...  
719    Petrol  
720    Diesel  
721    Petrol  
722    Diesel  
723    Diesel  

[724 rows x 6 columns]

In [66]:
car=car[car["Price"]<5000000]
car.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 723 entries, 0 to 723
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   name        723 non-null    object
 1   company     723 non-null    object
 2   year        723 non-null    object
 3   Price       723 non-null    int64 
 4   kms_driven  723 non-null    int64 
 5   fuel_type   723 non-null    object
dtypes: int64(2), object(4)
memory usage: 39.5+ KB


## Extacting training data

In [77]:
X=car[["name","company","year","kms_driven","fuel_type"]]

In [78]:
y=car.Price.values
y

array([  80000,  425000,  325000,  575000,  175000,  190000,  830000,
        250000,  182000,  315000,  415000,  320000, 1000000,  500000,
        350000,  160000,  310000,   75000,  100000,  190000,  290000,
         95000,  180000,  385000,  250000,  180000,  105000,  105000,
        650000,  689999,  448000,  549000,  501000,  489999,  280000,
        349999,  284999,  345000,  499999,  235000,  249999, 1475000,
        395000,  220000,  170000,   85000,  200000,  570000,  315000,
        110000,  501000,  448999, 1891111,  159500,  344999,  449999,
       1891111,  865000,  699000,  375000,  489999,  224999, 1200000,
        195000,  351000,  160000,  240000,   90000,  155000,  600000,
        189500,  350000,  210000,  390000,  135000, 1600000,  701000,
        265000,  525000,  372000,  635000,  550000,  575000,  485000,
        155000,  345000,  325000,  329500,  195000,  251111,  569999,
         69999,  299999,  220000,  399999,  450000,  270000,  350000,
        158400,  350

## Appliying train test split

In [79]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=0) #random_state=0.2 20% train 80 test

In [80]:
from sklearn.linear_model import LinearRegression


In [81]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import make_column_transformer
from sklearn.pipeline import make_pipeline
from sklearn.metrics import r2_score

# Pipelining

   ## creating OneHotencoder object to contain all the possible categories

In [83]:
ohe=OneHotEncoder()
ohe.fit(X[["name","company","year","fuel_type"]])

OneHotEncoder()

## creating a column transformer to transform categorical columns

In [84]:
column_trans=make_column_transformer((OneHotEncoder(categories=ohe.categories_),["name","company","year","fuel_type"]),remainder="passthrough")
#is ne Khud sb ko encode kr diya

## Linear regression model

In [85]:
lr = LinearRegression()

## making pipeline

In [86]:
pipe=make_pipeline(column_trans,lr)

## fitting the model

In [87]:
pipe.fit(X_train,y_train) 

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('onehotencoder',
                                                  OneHotEncoder(categories=[array(['Audi A3 Cabriolet', 'Audi A4 1.8', 'Audi A4 2.0', 'Audi A6 2.0',
       'Audi A8', 'Audi Q3 2.0', 'Audi Q5 2.0', 'Audi Q7', 'BMW 3 Series',
       'BMW 5 Series', 'BMW 7 Series', 'BMW X1', 'BMW X1 sDrive20d',
       'BMW X1 xDrive20d', 'Chevrolet Beat', 'Chevrolet Beat...
       '2003-01-01', '2004-01-01', '2005-01-01', '2006-01-01',
       '2007-01-01', '2008-01-01', '2009-01-01', '2010-01-01',
       '2011-01-01', '2012-01-01', '2013-01-01', '2014-01-01',
       '2015-01-01', '2016-01-01', '2017-01-01', '2018-01-01',
       '2019-01-01'], dtype=object),
                                                                            array(['Diesel', 'LPG', 'Petrol'], dtype=object)]),
                                                  ['name', 'company', 'year',
                                                   'fuel_type'])])),
                ('linearregression', LinearRegression())])

In [88]:
predictions = pipe.predict(X_train) 

In [89]:
pd.DataFrame({"original":y_train, 'pred':predictions})


original          pred
0      730000  6.994286e+05
1      295000  3.510717e+05
2      311000  3.608221e+05
3      644999  5.575240e+05
4       75000  2.740772e+05
..        ...           ...
573    290000  2.552415e+05
574   1400000  1.400139e+06
575    590000  4.754806e+05
576   1000000  5.146669e+05
577    175000  1.364493e+05

[578 rows x 2 columns]

## checking r2 score

In [90]:
from sklearn.metrics import r2_score
r2_score(y_train,predictions) #checking accuracy on training data

0.7812558809077329

In [91]:
from sklearn.metrics import mean_absolute_error as mae
mae(y_train,predictions)

111752.31610939448

## fitting the model with random state of train test split 

In [92]:
scores=[]
for i in range(1000):
    X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.1,random_state=i)
    lr=LinearRegression()
    pipe=make_pipeline(column_trans,lr)
    pipe.fit(X_train,y_train)
    y_pred=pipe.predict(X_train)
    scores.append(r2_score(y_train,y_pred))

In [93]:
import numpy as np

In [94]:
np.argmax(scores)

839

In [95]:
scores

[0.8202383238046708,
 0.8095084728469994,
 0.8186643018993354,
 0.8097665732750298,
 0.7930297301455574,
 0.8224545894404894,
 0.8028567723788428,
 0.8197564587365825,
 0.8000694057502348,
 0.8200384523115225,
 0.7924142282715975,
 0.7928556271003524,
 0.8060154589671915,
 0.8155273900232285,
 0.8020843584203609,
 0.8217947653339975,
 0.8190013397403867,
 0.8062849388618107,
 0.8189715085872408,
 0.8105900773294589,
 0.793027578710481,
 0.8137014908110294,
 0.797648668495153,
 0.8028791988990522,
 0.7838156646976296,
 0.8260758152534384,
 0.8161193229462558,
 0.802529461990002,
 0.8087438236558001,
 0.81333708160949,
 0.8079823016456,
 0.8087861739702484,
 0.8118009095538997,
 0.8180864048958192,
 0.7992645765781502,
 0.8286679549155791,
 0.8061510244925406,
 0.8179026983182511,
 0.829079884690407,
 0.8179723007726593,
 0.8213858701899818,
 0.8048970276971599,
 0.8019454137243973,
 0.8158936570428997,
 0.7745373482007356,
 0.8172665409625388,
 0.805925890756223,
 0.8155202500701542,
 0

In [96]:
scores[np.argmax(scores)]

0.8384149748366423

In [97]:
#for test data

In [98]:
predictions = pipe.predict(X_test) 

In [99]:
pd.DataFrame({"original":y_test, 'pred':predictions})

original           pred
0     650000  836875.763466
1     375000  429234.548656
2     265000  516763.887289
3     544999  556112.374528
4     365000  393555.349207
..       ...            ...
68    395000  361023.626713
69    182000  293236.945240
70    230000  255551.143454
71    399999  292146.036717
72    175000  302621.085679

[73 rows x 2 columns]

In [100]:
from sklearn.metrics import r2_score
r2_score(y_test,predictions) #checking accuracy on testing data

0.618384887030551

In [101]:

from sklearn.metrics import mean_absolute_error as mae
mae(y_test,predictions)

150474.7113918513

In [102]:
import numpy as np

In [103]:

scores=[]
for i in range(1000):
    X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.1,random_state=i)
    lr=LinearRegression()
    pipe=make_pipeline(column_trans,lr)
    pipe.fit(X_train,y_train)
    y_pred=pipe.predict(X_test)
    scores.append(r2_score(y_test,y_pred))

In [104]:
np.argmax(scores)

893

In [105]:
scores

[0.6653072745531988,
 0.7074509077013048,
 0.708709159599217,
 0.7936196336496679,
 0.4826622006330532,
 0.4597327745169806,
 0.763946530566446,
 0.5327121541453739,
 0.4771638737814462,
 0.5682611551093347,
 0.7660419865512789,
 0.711762766862968,
 0.831001794033242,
 0.706625363463794,
 0.592026199379958,
 0.22495790353361034,
 0.7328252481180245,
 0.8131017400977517,
 0.5828264944130792,
 0.734411259862797,
 0.600244491568753,
 0.46242127207219985,
 0.294308794638627,
 0.3950503949209744,
 0.5326841606114944,
 0.5587868125934983,
 0.4884046529764092,
 0.49459101828342156,
 0.5040910084866005,
 0.6646893197997639,
 0.6951247748689433,
 0.6690992160178277,
 0.5399541571801862,
 0.5287597962727044,
 0.3514882954410453,
 0.4591338517515192,
 0.6274607892340629,
 0.4640984655364102,
 0.4566174656899049,
 0.4182942309591634,
 0.589706357152334,
 0.618508445111176,
 0.6353915152586698,
 0.6068568792694509,
 0.6633270244353151,
 0.2165144488106493,
 0.7570758089014854,
 0.6782858373309975,


In [106]:
scores[np.argmax(scores)]

0.9007107199561958

In [107]:
scores=[]
for i in range(1000):
    X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.1,random_state=893)
    lr=LinearRegression()
    pipe=make_pipeline(column_trans,lr)
    pipe.fit(X_train,y_train)
    y_pred=pipe.predict(X_test)
    scores.append(r2_score(y_test,y_pred))


In [108]:
X_test.columns


Index(['name', 'company', 'year', 'kms_driven', 'fuel_type'], dtype='object')

In [109]:
data=np.array(["Tata Indica V2","Tata","2009-01-01","30000","Diesel"])

In [110]:
record=pd.DataFrame(columns=X_test.columns,data=[["Tata Indica V2","Tata","2009-01-01","30000","Diesel"]])

In [111]:
pipe.predict(record)

array([69431.85160375])

In [112]:
pipe.predict(pd.DataFrame(columns=['name','company','year','kms_driven','fuel_type'],data=np.array(["Tata Indica V2","Tata","2009-01-01","30000","Diesel"]).reshape(1,5)))

array([69431.85160375])