# Supervised learning (we find accuracy)
- Classification 
(1.accuracy
-2.Preci+sion
-3.Recall)
>>logistic regression
>>decision trees
>>naive baise   #Recall=Tp/(Tp+Fn) works on bias

>>Random forest
K-nearest Neighbours
SVM

In [28]:
import numpy as np
import pandas as pd

In [29]:
from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import MinMaxScaler
from sklearn.pipeline import Pipeline,make_pipeline
from sklearn.feature_selection import SelectKBest,chi2
from sklearn.tree import DecisionTreeClassifier

In [30]:
df = pd.read_csv('diabetes.csv')

In [31]:
df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [32]:
X_train,X_test,y_train,y_test = train_test_split(df.drop(columns=['Outcome']),
                                                 df['Outcome'],
                                                 test_size=0.2,
                                                random_state=42) 

In [33]:
X_train.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
60             2       84              0              0        0   0.0   
618            9      112             82             24        0  28.2   
346            1      139             46             19       83  28.7   
294            0      161             50              0        0  21.9   
231            6      134             80             37      370  46.2   

     DiabetesPedigreeFunction  Age  
60                      0.304   21  
618                     1.282   50  
346                     0.654   22  
294                     0.254   65  
231                     0.238   46

In [34]:
y_train.sample(5)

40     0
613    0
138    0
231    1
532    0
Name: Outcome, dtype: int64

In [37]:
y_train.head()

60     0
618    1
346    0
294    0
231    1
Name: Outcome, dtype: int64

In [35]:
df.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [38]:

# Scaling
trf3 = ColumnTransformer([
    ('scale',MinMaxScaler(),slice(0,10))
])


In [39]:
# train the model
trf5 = DecisionTreeClassifier()

In [40]:
pipe = Pipeline([ #list name and object
                ('trf3',trf3),
                ('trf5',trf5)
            ])

In [41]:
pipe.fit(X_train,y_train)

Pipeline(steps=[('trf3',
                 ColumnTransformer(transformers=[('scale', MinMaxScaler(),
                                                  slice(0, 10, None))])),
                ('trf5', DecisionTreeClassifier())])

In [42]:
import pickle
import numpy as np

In [43]:
# export 

pickle.dump(pipe,open('diabeties.pkl','wb')) #wb = write binary pura pipe write hoga but wo binary form me he

In [44]:
 #for reading 

with open('diabeties.pkl', 'rb') as file:
    loaded_pipe = pickle.load(file)


In [45]:
#assume user input
test_input2=np.array([[0,137,40,35,168,43.1,2.288,33]])

In [50]:
pipe.predict(test_input2)

/Users/muhammadbilal/anaconda3/lib/python3.11/site-packages/sklearn/base.py:464: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  warnings.warn(


array([1])

In [51]:
predictions = pipe.predict(X_test)

In [53]:
predictionss = pipe.predict(X_train)

In [54]:
y_test.value_counts

<bound method IndexOpsMixin.value_counts of 668    0
324    0
624    0
690    0
473    0
      ..
355    1
534    0
344    0
296    1
462    0
Name: Outcome, Length: 154, dtype: int64>

In [55]:
from sklearn.metrics import r2_score
r2_score(y_train,predictionss)

1.0

In [56]:
predictionss#train data

array([0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0,
       0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1,
       1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1,
       0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0,

In [57]:
y_train.value_counts

<bound method IndexOpsMixin.value_counts of 60     0
618    1
346    0
294    0
231    1
      ..
71     0
106    0
270    1
435    1
102    0
Name: Outcome, Length: 614, dtype: int64>

In [58]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,predictions)

0.7467532467532467

In [59]:
pd.DataFrame({'y_test':y_test, 'y_pred':predictions})

y_test  y_pred
668       0       1
324       0       0
624       0       0
690       0       0
473       0       0
..      ...     ...
355       1       1
534       0       0
344       0       1
296       1       0
462       0       0

[154 rows x 2 columns]

In [90]:
y_train.value_counts()

0    401
1    213
Name: Outcome, dtype: int64

In [60]:
#accuracy formula =(Tp+Tn)/(Tp+Tn+Fp+Fn)
#precision positive bolne me accuracy kitni he precision = Tp/(Tp+Fp)
#Recall=Tp/(Tp+Fn)

In [61]:
from sklearn.metrics import classification_report
print(classification_report(y_test, predictions))



              precision    recall  f1-score   support

           0       0.83      0.77      0.80        99
           1       0.63      0.71      0.67        55

    accuracy                           0.75       154
   macro avg       0.73      0.74      0.73       154
weighted avg       0.76      0.75      0.75       154



In [93]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, predictions))

[[78 21]
 [14 41]]


In [62]:
recall=78/(78+14)
recall

0.8478260869565217

In [63]:
p=78/(78+21)
p

0.7878787878787878